# Generated by Django 3.2.5 on 2021-07-25 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_auto_20210725_0534'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FollowSinger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.singer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.listener')),
            ],
        ),
    ]
