# Generated by Django 3.2.6 on 2021-08-05 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowSinger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.singer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.listener')),
            ],
        ),
        migrations.CreateModel(
            name='FollowPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlists.playlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.listener')),
            ],
        ),
    ]
