# Generated by Django 3.2.5 on 2021-07-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singer',
            name='user',
        ),
        migrations.AddField(
            model_name='singer',
            name='name',
            field=models.CharField(default='خواننده', max_length=16),
        ),
    ]
