# Generated by Django 3.2.5 on 2021-07-25 05:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210725_0534'),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='cover',
            field=models.ImageField(default='default', upload_to='', verbose_name='cover'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='music',
            name='file_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='music',
            name='file_type',
            field=models.CharField(choices=[('podcast', 'podcast'), ('music', 'music')], default='music', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='music',
            name='lenght',
            field=models.IntegerField(default=1, verbose_name='time in seconds'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='music',
            name='played_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='music',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.provider'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='music',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='music',
            name='singer',
        ),
        migrations.AddField(
            model_name='music',
            name='singer',
            field=models.ManyToManyField(to='accounts.Singer'),
        ),
    ]
